name: codesign
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mkl=2024.0.0
  - numpy=1.21.0
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - matplotlib=3.7.1
  - tqdm=4.66.4
  - tensorboard=2.14.0
  - protobuf=4.25.3
  - pyyaml=6.0.3
  - pip
  - pip:
    - cma==4.2.0
    - torchviz==0.0.3
    - pytest==8.3.5
    - flake8==7.1.2
    - mujoco==3.2.3
