name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-22.04]
        include:
          - os: ubuntu-22.04
            shell: bash -el {0}
            cache_path: ~/conda_pkgs_dir

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    env:
      CONDA_PKGS_DIRS: ${{ matrix.cache_path }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache conda packages
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: ${{ matrix.cache_path }}
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os }}-conda-

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        activate-environment: codesign
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install mups-codesign package
      run: |
        pip install -e .

    - name: Check syntax errors
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests
      run: |
        pytest tests/ -v -s
